ev3dev/dc_motor.go
ev3dev/demo/demo.go
ev3dev/ev3dev.go
ev3dev/led.go
ev3dev/lego_port.go
ev3dev/linear_actuator.go
ev3dev/sensor.go
ev3dev/servo_motor.go
ev3dev/tacho_motor.go

ev3dev: allow fluent style API use

---

ev3dev/ev3dev.go

ev3dev: add IsConnected function

---

ev3dev/dc_motor.go
ev3dev/ev3dev.go
ev3dev/examples/find/find.go
ev3dev/examples/findafter/findafter.go
ev3dev/lego_port.go
ev3dev/linear_actuator.go
ev3dev/sensor.go
ev3dev/servo_motor.go
ev3dev/tacho_motor.go

ev3dev: add Find and FindAfter functions

---

ev3dev.go

This change makes `ev3dev.Wait` dependent on `sysfs_notify` support in the kernel which does not currently exist - using this code would prevent timeouts from being meaningful. There are two options, 1) wait until the `sysfs_notify` support is merged and only support kernels at or above that version, 2) somehow detect the kernel version and only poll when it is meaningful.

ev3dev: fix Wait for functional sysfs poll support

---

ev3dev.go
linear_actuator.go
servo_motor.go
tacho_motor.go

@vladimir-ch Please take a look.

ev3dev: fix issues raised in #23

---

dc_motor.go

ev3dev: fix lagging state attribute for DCMotor

---

README.md
ev3dev.go
export_test.go
wait_test.go

ev3dev: test motor state waiting

---

AUTHORS
CONTRIBUTORS
ev3dev.go
wait_linux.go
wait_other.go

ev3dev: add build tags for compilation on other OS

---

sensor.go

ev3dev: replace missed opaque attribute accessor error

---

sensor_test.go

ev3dev: fix race in direct bytes return

---

errors.go
errors_test.go
lego_port.go

ev3dev: remove opaque error from LegoPort

---

examples/gps/gps.go
otheri2c/dgps.go

otheri2c: new package for Other/I2C handling

---

motorutil/steer.go
motorutil/steer_test.go

@dlech Please take a look.
Fixes #57.

motorutil: add stop action handling to Steerer

---

ev3dev.go
export_test.go
sensor.go
sensor_test.go

ev3dev: add firmware version accessor

---

ev3dev.go
examples/find/find.go
examples/znap/znap.go
sensor.go
sensor_test.go

@dlech Please take a look.
Fixes #54.
Closes #53.
See #63.

ev3dev: sensor attribute caching

---

lego_port.go
lego_port_test.go

@dlech Please take a look.
Fixes #66.

ev3dev: fix lego-port caching

---

errors.go
ev3dev.go
lego_port.go

@dlech Please take a look.
Fixes #63.
Updates #24.

ev3dev: only allow one handle per device for motors, ports and sensors

---

README.md

Forgot to fix system path issue for Buttons in README.md
Now it will be fixed...

fixed Buttons system path in README.md

---

.travis.yml
errors.go
errors_nowrap.go
errors_test.go
errors_wrap.go
ev3dev.go

ev3dev: update for go1.13

---

dc_motor_test.go
ev3dev.go
ev3dev_test.go
export_test.go
led_test.go
lego_port_test.go
linear_actuator_test.go
power_supply_test.go
sensor.go
sensor_test.go
servo_motor_test.go
tacho_motor_test.go
wait_test.go

This is a counter proposal for #94.
It's not exactly how I'd like it to be, but after several hours dealing with FUSE-based kernel hangs I think it's the best that I'm likely to get to for a while.
Please take a look.
/cc @FlorianRaediker
Closes #94.

ev3dev: use file registry to reduce file opening costs
